### ISSUE TITLE
backlog

### ISSUE THREAD

**Issue by AdnanBennasare** [labs-web/lab-rapport#95]
# Backlog

## Travail à faire

- Création de la liste des tâches
- Validation avec le formateur
- Création des issues
- Changement les noms des fichier dans le dossier backlog :
    - Ordre.Titre_issue.Numero_issue.md
- Les issues sont enregistrer dans des sous-dossiers qui représente des labels des issues

## Livrable 

- backlog/*
- README.md

**Comment by essarraj-fouad** [comment]
Les fichiers pptx pour les images ne sont plus demandés, sauf pour les diagrammes : carte d'empathie, cas d'utilisation
